In [14]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler, StandardScaler, OneHotEncoder
from sklearn.datasets import load_iris

In [3]:
data = np.array([[1, -1, 2], [3, 0, 0], [0, 2, -1]])
data

array([[ 1, -1,  2],
       [ 3,  0,  0],
       [ 0,  2, -1]])

In [4]:
scaler = MinMaxScaler()
data_escalada = scaler.fit_transform(data)
data_escalada

array([[0.33333333, 0.        , 1.        ],
       [1.        , 0.33333333, 0.33333333],
       [0.        , 1.        , 0.        ]])

In [9]:
iris = load_iris()
X = iris.data
X[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [10]:
X_escalado = scaler.fit_transform(X)
X_escalado[:5]

array([[0.22222222, 0.625     , 0.06779661, 0.04166667],
       [0.16666667, 0.41666667, 0.06779661, 0.04166667],
       [0.11111111, 0.5       , 0.05084746, 0.04166667],
       [0.08333333, 0.45833333, 0.08474576, 0.04166667],
       [0.19444444, 0.66666667, 0.06779661, 0.04166667]])

In [12]:
scaler2 = StandardScaler()
data_escalada2 = scaler2.fit_transform(data)
data_escalada2

array([[-0.26726124, -1.06904497,  1.33630621],
       [ 1.33630621, -0.26726124, -0.26726124],
       [-1.06904497,  1.33630621, -1.06904497]])

In [13]:
categorias = np.array([['rojo'], ['verde'], ['azul'], ['amarillo'], ['violeta'], ['naranja']])
categorias

array([['rojo'],
       ['verde'],
       ['azul'],
       ['amarillo'],
       ['violeta'],
       ['naranja']], dtype='<U8')

In [17]:
encoder = OneHotEncoder(sparse_output=False)
data_codificada = encoder.fit_transform(categorias)
data_codificada

array([[0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0., 0.]])