In [1]:
import numpy as np

In [2]:
array1 = np.array([1, 2, 3])
array1

array([1, 2, 3])

In [3]:
array2 = np.array([[0], [10], [20], [30]])
array2

array([[ 0],
       [10],
       [20],
       [30]])

In [6]:
broadcast_suma = array2 + array1
broadcast_suma

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

¿Cómo funciona la suma al ser arrays tan distintos?

Es la suma del elemento 0 del `array2` más el elemento 1 del `array1` = 1, la suma del elemento 0 del `array2` más el elemento 2 del `array1` = 2, la suma del elemento 0 del `array2` más el elemento 3 del `array1` = 3, después se pasa a la segunda fila del `array2`, la suma del elemento 10 del `array2` más el elemento 1 del `array1` = 11, la suma del elemento 10 del `array2` más el elemento 2 del `array1` = 12, la suma del elemento 10 del `array2` más el elemento 3 del `array1` = 13 y vicerversa con las démas lineas

In [8]:
broadcast_multi = array2 * array1 # se sigue la misma corriente array2[0] * array1[0], array2[0] * array1[1], array2[0] * array1[2], ...
broadcast_multi

array([[ 0,  0,  0],
       [10, 20, 30],
       [20, 40, 60],
       [30, 60, 90]])

In [11]:
# universal functions

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [13]:
resultado = np.add(a, b)
resultado

array([5, 7, 9])

In [14]:
# .substract(), .multiply(), .divide()

In [15]:
resultado2 = np.exp(a)
resultado2

array([ 2.71828183,  7.3890561 , 20.08553692])

In [16]:
resultado3 = np.log(a)
resultado3

array([0.        , 0.69314718, 1.09861229])

In [20]:
resultado4 = np.log10(a)
resultado4

array([0.        , 0.30103   , 0.47712125])

In [24]:
resultado5 = np.sqrt(a)
resultado5

array([1.        , 1.41421356, 1.73205081])